language: erlang

otp_release:
  - 18.0

sudo: false

addons:
  apt:
    packages:
      - autoconf
      - libncurses-dev
      - build-essential
      - libssl-dev
      - libwxgtk2.8-dev
      - libgl1-mesa-dev
      - libglu1-mesa-dev
      - libpng3
      - default-jdk
      - g++
      - xsltproc

before_script:
  - set -e
  - export ERL_TOP=$PWD
  - export PATH=$ERL_TOP/bin:$PATH
  - export ERL_LIBS=''
  - export MAKEFLAGS=-j6
  - kerl_deactivate

script:
  - ./scripts/build-otp
  
after_success:
  - $ERL_TOP/bin/dialyzer --build_plt --apps asn1 compiler crypto dialyzer edoc erts et hipe inets kernel mnesia observer public_key runtime_tools snmp ssh ssl stdlib syntax_tools wx xmerl --statistics
  - $ERL_TOP/bin/dialyzer -n -Wunknown -Wunmatched_returns --apps compiler erts kernel stdlib asn1 crypto dialyzer hipe parsetools public_key runtime_tools sasl tools --statistics
  - $ERL_TOP/bin/dialyzer -n --apps common_test debugger edoc inets mnesia observer ssh ssl syntax_tools tools wx xmerl --statistics
  - ./otp_build tests && make release_docs

after_script:
  - ./scripts/run-smoke-tests
